const CARTOON_CHARACTERS=[{name:"SpongeBob SquarePants",pass:"gary123",studyQuotes:["I'm ready! 🍍","Knowledge is power!"],relaxQuotes:["Barnacles! Break time.","Blowing bubbles... 🫧"]},{name:"Patrick Star",pass:"wumbo_forever",studyQuotes:["Look, I'm using my brain! 🧠"],relaxQuotes:["My brain hurts. Going to sleep. 💤","Is there any burger left? 🍔"]},{name:"Squidward Tentacles",pass:"i_hate_everyone",studyQuotes:["Silence! I am trying to study here."],relaxQuotes:["Time for my clarinet practice. 🎷","I hate working."]},{name:"Shrek",pass:"onion_layers",studyQuotes:["Get out of my swamp, I'm reading!","Studying has layers."],relaxQuotes:["I need a mud bath. 🪵","Time to find Donkey."]},{name:"Donkey",pass:"waffles55",studyQuotes:["I'm doing science, Shrek!","Look at me go!"],relaxQuotes:["Are we smart yet? 🐴","I'm making waffles! 🧇"]},{name:"Rick Sanchez",pass:"wubbalubbadubdub",studyQuotes:["This exam is multi-dimensionally easy. 🧪"],relaxQuotes:["I'm bored. Going to a sci-fi festival.","Morty, grab your coat."]},{name:"Morty Smith",pass:"jessica_love",studyQuotes:["Oh jeez, I'm understanding physics!"],relaxQuotes:["Aw man, anxiety hitting. Break time. 🛋️"]},{name:"Homer Simpson",pass:"donut_king",studyQuotes:["Mmm... forbidden knowledge... 🍩"],relaxQuotes:["Woohoo! Break time! 📺","D'oh! I read the wrong page!"]},{name:"Naruto Uzumaki",pass:"hokage2026",studyQuotes:["Believe it! This book won't defeat me! 🦊"],relaxQuotes:["RAMEN TIME! 🍜","Shadow clone jutsu!"]},{name:"Saitama",pass:"one_punch_man",studyQuotes:["100 pages read, every single day!"],relaxQuotes:["I missed the supermarket sale! 🛒","Playing video games."]}];
const EXTRA_CHARACTERS=["Mr. Krabs","Sandy Cheeks","Fiona","Puss in Boots","Mickey Mouse","Donald Duck","Goofy","Scooby-Doo","Shaggy Rogers","Fred Jones","Daphne Blake","Velma Dinkley","Ben Tennyson","Gwen Tennyson","Kevin Levin","Grandpa Max","Marge Simpson","Bart Simpson","Lisa Simpson","Peter Griffin","Stewie Griffin","Brian Griffin","Buzz Lightyear","Sheriff Woody","Lightning McQueen"];
let onlineBots={};let bannedBots=[];let userStatus="Studying";let userSeconds=0;let timerInterval=null;let myName="Amir";
let configMaxMembers=10;let configSelectionMode="random";let configSelectedPool=[];let configAllowOthers=true;let configAllowLeave=true;let configAllowRejoin=true;
let userCoins=0;let coffeeStock=0;const COFFEE_PRICE=20;const COINS_PER_MINUTE=2;const ENERGY_DRAIN_INTERVAL=45;const ENERGY_RECOVER_INTERVAL=60;const COFFEE_WAIT_SECONDS=120;
let multiplayerSyncInterval=null;let lastSeenMessages={};let mpRoomMeta=null;

// --- Session persistence ---
function saveSession(data){localStorage.setItem('cozy_session',JSON.stringify({...data,savedAt:Date.now()}));}
function loadSession(){try{return JSON.parse(localStorage.getItem('cozy_session'))||null;}catch(e){return null;}}
function clearSession(){localStorage.removeItem('cozy_session');}

const loginScreen=document.getElementById('login-screen');const appScreen=document.getElementById('app-screen');const toggleAdvancedBtn=document.getElementById('toggle-advanced');const advancedPanel=document.getElementById('advanced-panel');const charSelectionMode=document.getElementById('char-selection-mode');const manualCharsWrapper=document.getElementById('manual-chars-wrapper');const charsCheckboxList=document.getElementById('chars-checkbox-list');const allowLeaveCheckbox=document.getElementById('allow-leave');const rejoinWrapper=document.getElementById('rejoin-wrapper');const presetHistorySelect=document.getElementById('preset-history');const btnClearHistory=document.getElementById('btn-clear-history');const btnToggleCreator=document.getElementById('btn-toggle-creator');const characterCreatorPanel=document.getElementById('character-creator-panel');const btnSaveCustomChar=document.getElementById('btn-save-custom-char');const adminModal=document.getElementById('admin-modal');const btnAdminPanel=document.getElementById('btn-admin-panel');const btnCloseAdmin=document.getElementById('btn-close-admin');const adminUsersList=document.getElementById('admin-users-list');const shopModal=document.getElementById('shop-modal');const btnShop=document.getElementById('btn-shop');const btnCloseShop=document.getElementById('btn-close-shop');const btnBuyCoffee=document.getElementById('btn-buy-coffee');

// --- Restore session on load ---
window.addEventListener('load',()=>{const sess=loadSession();if(sess&&sess.mode==='solo'&&sess.userName){restoreSoloSession(sess);}else if(sess&&sess.mode==='multi'&&sess.roomId&&sess.userName){restoreMultiSession(sess);}else{checkUrlRoom();}});

function checkUrlRoom(){const urlParams=new URLSearchParams(window.location.search);const autoRoomId=urlParams.get('room');if(autoRoomId){document.getElementById('join-room-id').value=autoRoomId;setTimeout(()=>{document.getElementById('btn-join-mode').click();document.getElementById('btn-study-friends').click();},300);}}

function restoreSoloSession(sess){myName=sess.userName;userSeconds=sess.userSeconds||0;userCoins=sess.userCoins||0;coffeeStock=sess.coffeeStock||0;configMaxMembers=sess.configMaxMembers||10;configSelectionMode=sess.configSelectionMode||'random';configSelectedPool=sess.configSelectedPool||[];configAllowOthers=sess.configAllowOthers!==undefined?sess.configAllowOthers:true;configAllowLeave=sess.configAllowLeave!==undefined?sess.configAllowLeave:true;configAllowRejoin=sess.configAllowRejoin!==undefined?sess.configAllowRejoin:true;applyTheme(sess.theme||'cyan');document.getElementById('display-username').innerText=myName;loginScreen.classList.add('hidden');appScreen.classList.remove('hidden');btnAdminPanel.style.display='block';document.getElementById('user-timer').innerText=formatTime(userSeconds);updateShopDisplay();initRoom();}

async function restoreMultiSession(sess){myName=sess.userName;userSeconds=sess.userSeconds||0;userCoins=sess.userCoins||0;coffeeStock=sess.coffeeStock||0;applyTheme(sess.theme||'cyan');document.getElementById('display-username').innerText=myName;try{const meta=await getRoomMeta(sess.roomId);if(!meta)throw new Error('expired');mpRoomMeta=meta;await joinRoom(sess.roomId,sess.roomPassword,myName);loginScreen.classList.add('hidden');appScreen.classList.remove('hidden');if(sess.isHost){btnAdminPanel.style.display='block';}updateShopDisplay();document.getElementById('user-timer').innerText=formatTime(userSeconds);startMultiplayerTimers(sess.isHost);}catch(e){clearSession();checkUrlRoom();}}

function applyTheme(t){let c="#00ffff";if(t==="magenta")c="#ff007f";else if(t==="green")c="#2ecc71";else if(t==="yellow")c="#f1c40f";else if(t==="purple")c="#9b59b6";else if(t==="orange")c="#e67e22";else if(t==="red")c="#e74c3c";else if(t==="white")c="#f8fafc";document.documentElement.style.setProperty('--theme-main',c);}

toggleAdvancedBtn.addEventListener('click',()=>{advancedPanel.classList.toggle('hidden');});
document.getElementById('toggle-host-advanced').addEventListener('click',()=>{document.getElementById('host-advanced-panel').classList.toggle('hidden');});
charSelectionMode.addEventListener('change',(e)=>{if(e.target.value==="custom"){manualCharsWrapper.classList.remove('hidden');renderCharacterCheckboxes();}else{manualCharsWrapper.classList.add('hidden');}});
btnToggleCreator.addEventListener('click',()=>{characterCreatorPanel.classList.toggle('hidden');});
btnSaveCustomChar.addEventListener('click',()=>{const name=document.getElementById('new-char-name').value.trim();const pass=document.getElementById('new-char-pass').value.trim()||"pass123";const studyStr=document.getElementById('new-char-study').value.trim();const relaxStr=document.getElementById('new-char-relax').value.trim();if(!name){alert("Please enter a character name!");return;}const studyQuotes=studyStr?studyStr.split('|').map(q=>q.trim()):["Let's study hard! 📖"];const relaxQuotes=relaxStr?relaxStr.split('|').map(q=>q.trim()):["Taking a quick coffee break ☕"];const newCharObj={name,pass,studyQuotes,relaxQuotes,isCustom:true};let customPool=JSON.parse(localStorage.getItem('cozy_custom_chars'))||[];customPool=customPool.filter(c=>c.name.toLowerCase()!==name.toLowerCase());customPool.push(newCharObj);localStorage.setItem('cozy_custom_chars',JSON.stringify(customPool));document.getElementById('new-char-name').value="";document.getElementById('new-char-pass').value="";document.getElementById('new-char-study').value="";document.getElementById('new-char-relax').value="";characterCreatorPanel.classList.add('hidden');renderCharacterCheckboxes();});
window.deleteCustomCharacter=function(name){if(confirm(`Are you sure you want to completely delete "${name}"?`)){let customPool=JSON.parse(localStorage.getItem('cozy_custom_chars'))||[];customPool=customPool.filter(c=>c.name!==name);localStorage.setItem('cozy_custom_chars',JSON.stringify(customPool));renderCharacterCheckboxes();}};
function getAllCharacters(){const customPool=JSON.parse(localStorage.getItem('cozy_custom_chars'))||[];return[...CARTOON_CHARACTERS,...customPool];}
function renderCharacterCheckboxes(){charsCheckboxList.innerHTML="";const allChars=getAllCharacters();allChars.forEach(char=>{const row=document.createElement('div');row.className="checkbox-item-row";let deleteBtnHTML="";if(char.isCustom){deleteBtnHTML=`<button type="button" class="btn-delete-char" onclick="deleteCustomCharacter('${char.name}')" title="Delete Character">❌</button>`;}row.innerHTML=`<label class="pixel-checkbox"><input type="checkbox" class="bot-selector-check" value="${char.name}" checked><span class="checkmark"></span> ${char.name}</label>${deleteBtnHTML}`;charsCheckboxList.appendChild(row);});}
allowLeaveCheckbox.addEventListener('change',(e)=>{if(!e.target.checked)rejoinWrapper.classList.add('hidden');else rejoinWrapper.classList.remove('hidden');});
document.addEventListener('DOMContentLoaded',loadPresetsFromStorage);
function loadPresetsFromStorage(){const saved=JSON.parse(localStorage.getItem('cozy_presets'))||{};presetHistorySelect.innerHTML='<option value="default">✨ Default Cozy Room</option>';for(let name in saved){const opt=document.createElement('option');opt.value=name;opt.innerText=`⏳ [History] ${name}`;presetHistorySelect.appendChild(opt);}}
btnClearHistory.addEventListener('click',()=>{if(confirm("Are you sure you want to wipe all history/presets?")){localStorage.removeItem('cozy_presets');loadPresetsFromStorage();presetHistorySelect.value="default";document.getElementById('username').value="";document.getElementById('theme-color').value="cyan";document.getElementById('max-members').value="10";charSelectionMode.value="random";manualCharsWrapper.classList.add('hidden');document.getElementById('new-preset-name').value="";}});
presetHistorySelect.addEventListener('change',(e)=>{if(e.target.value==="default"){document.getElementById('username').value="";document.getElementById('theme-color').value="cyan";document.getElementById('max-members').value="10";charSelectionMode.value="random";manualCharsWrapper.classList.add('hidden');document.getElementById('new-preset-name').value="";return;}const saved=JSON.parse(localStorage.getItem('cozy_presets'))||{};const preset=saved[e.target.value];if(preset){document.getElementById('username').value=preset.user||"";document.getElementById('theme-color').value=preset.theme||"cyan";document.getElementById('max-members').value=preset.max;charSelectionMode.value=preset.mode;document.getElementById('allow-others').checked=preset.allowOthers;allowLeaveCheckbox.checked=preset.allowLeave;document.getElementById('allow-rejoin').checked=preset.allowRejoin;if(preset.mode==="custom"){manualCharsWrapper.classList.remove('hidden');renderCharacterCheckboxes();document.querySelectorAll('.bot-selector-check').forEach(chk=>{chk.checked=preset.selectedPool.includes(chk.value);});}else{manualCharsWrapper.classList.add('hidden');}advancedPanel.classList.remove('hidden');}});

document.getElementById('btn-enter').addEventListener('click',()=>{myName=document.getElementById('username').value.trim();const currentThemeColor=document.getElementById('theme-color').value;if(myName===""){alert("Enter your name!");return;}configMaxMembers=parseInt(document.getElementById('max-members').value)||10;configSelectionMode=charSelectionMode.value;configAllowOthers=document.getElementById('allow-others').checked;configAllowLeave=allowLeaveCheckbox.checked;configAllowRejoin=document.getElementById('allow-rejoin').checked;const allChars=getAllCharacters();if(configSelectionMode==="custom"){configSelectedPool=[];document.querySelectorAll('.bot-selector-check:checked').forEach(chk=>{configSelectedPool.push(chk.value);});if(configSelectedPool.length===0){alert("Pick at least one character!");return;}}else{configSelectedPool=allChars.map(c=>c.name);}const presetNameInput=document.getElementById('new-preset-name').value.trim();if(presetHistorySelect.value!=="default"||presetNameInput!==""){const saveName=presetNameInput!==""?presetNameInput:`Room_${myName}_${Math.floor(Math.random()*100)}`;const saved=JSON.parse(localStorage.getItem('cozy_presets'))||{};saved[saveName]={user:myName,theme:currentThemeColor,max:configMaxMembers,mode:configSelectionMode,selectedPool:configSelectedPool,allowOthers:configAllowOthers,allowLeave:configAllowLeave,allowRejoin:configAllowRejoin};localStorage.setItem('cozy_presets',JSON.stringify(saved));}applyTheme(currentThemeColor);document.getElementById('display-username').innerText=myName;loginScreen.classList.add('hidden');appScreen.classList.remove('hidden');btnAdminPanel.style.display='block';saveSession({mode:'solo',userName:myName,theme:currentThemeColor,userSeconds,userCoins,coffeeStock,configMaxMembers,configSelectionMode,configSelectedPool,configAllowOthers,configAllowLeave,configAllowRejoin});initRoom();});

document.getElementById('btn-pause').addEventListener('click',()=>{if(userStatus==="Studying"){userStatus="Relaxing";document.getElementById('user-status-badge').innerText="Relaxing ⏳";document.getElementById('user-status-badge').className="status-badge relaxing";addSystemMessage("☕ You are taking a break.","system-msg");}else{userStatus="Studying";document.getElementById('user-status-badge').innerText="Studying 📖";document.getElementById('user-status-badge').className="status-badge studying";addSystemMessage("📖 You resumed studying!","system-msg");}updateMemberList();});

// --- Power button ---
document.getElementById('btn-power').addEventListener('click',async()=>{if(isInMultiplayer()){if(getIsHost()){if(!confirm("Leaving will DELETE the room for everyone. Are you sure?")){return;}await leaveRoomGracefully(myName,true);}else{await leaveRoomGracefully(myName,false);}clearInterval(timerInterval);clearInterval(multiplayerSyncInterval);}else{clearInterval(timerInterval);}clearSession();onlineBots={};bannedBots=[];userStatus="Studying";userSeconds=0;userCoins=0;coffeeStock=0;appScreen.classList.add('hidden');loginScreen.classList.remove('hidden');btnAdminPanel.style.display='none';document.getElementById('user-status-badge').innerText="Studying 📖";document.getElementById('user-status-badge').className="status-badge studying";document.getElementById('user-timer').innerText="00:00:00";addSystemMessage("ℹ️ Room initialized. Welcome!","system-msg");document.getElementById('chat-messages').innerHTML='<div class="message system-msg">ℹ️ Room initialized. Welcome!</div>';document.getElementById('member-list').innerHTML='';});

window.onRoomDeleted=function(){clearInterval(timerInterval);clearInterval(multiplayerSyncInterval);clearSession();alert("⚠️ The room was deleted by the host.");appScreen.classList.add('hidden');loginScreen.classList.remove('hidden');btnAdminPanel.style.display='none';};

btnShop.addEventListener('click',()=>{updateShopDisplay();shopModal.classList.remove('hidden');});
btnCloseShop.addEventListener('click',()=>{shopModal.classList.add('hidden');});
btnBuyCoffee.addEventListener('click',()=>{if(userCoins<COFFEE_PRICE){addSystemMessage(`💰 Not enough coins! Need ${COFFEE_PRICE}, you have ${Math.floor(userCoins)}.`,"system-msg");return;}userCoins-=COFFEE_PRICE;coffeeStock++;updateShopDisplay();addSystemMessage(`☕ You bought a coffee! Stock: ${coffeeStock}`,"system-msg");});
function updateShopDisplay(){document.getElementById('shop-coin-display').innerText=Math.floor(userCoins);document.getElementById('shop-coffee-display').innerText=coffeeStock;}

function initRoom(){let availablePool=[...configSelectedPool];const initialCount=Math.min(configMaxMembers-1,availablePool.length,6);const shuffled=availablePool.sort(()=>0.5-Math.random()).slice(0,initialCount);const allChars=getAllCharacters();shuffled.forEach(name=>{const fullData=allChars.find(c=>c.name===name);onlineBots[name]={status:Math.random()>0.3?"Studying":"Relaxing",timeSpent:Math.floor(Math.random()*45)+5,energy:Math.floor(Math.random()*40)+60,energyTickStudy:0,energyTickRelax:0,coffeeWaiting:false,coffeeWaitSeconds:0,coffeeMessageId:null,quotes:fullData||null,pass:fullData?fullData.pass:"pass_"+Math.floor(Math.random()*999),isFrozen:false,isLocked:false};});updateMemberList();timerInterval=setInterval(()=>{if(userStatus==="Studying"){userSeconds++;userCoins+=COINS_PER_MINUTE/60;document.getElementById('user-timer').innerText=formatTime(userSeconds);}tickBots();if(userSeconds%5===0){updateMemberList();saveSession({mode:'solo',userName:myName,theme:document.getElementById('theme-color')?.value||'cyan',userSeconds,userCoins,coffeeStock,configMaxMembers,configSelectionMode,configSelectedPool,configAllowOthers,configAllowLeave,configAllowRejoin});}else{updateMemberTimesOnly();}},1000);simulateRoomActivities();}

function tickBots(){for(let bot in onlineBots){const b=onlineBots[bot];if(b.isFrozen)continue;if(b.status==="Studying"&&!b.coffeeWaiting){b.timeSpent+=1/60;b.energyTickStudy=(b.energyTickStudy||0)+1;if(b.energyTickStudy>=ENERGY_DRAIN_INTERVAL){b.energy=Math.max(0,b.energy-1);b.energyTickStudy=0;if(b.energy===0&&!b.coffeeWaiting){triggerCoffeeRequest(bot);}}}else if(b.status==="Relaxing"&&!b.coffeeWaiting){b.energyTickRelax=(b.energyTickRelax||0)+1;if(b.energyTickRelax>=ENERGY_RECOVER_INTERVAL){b.energy=Math.min(100,b.energy+1);b.energyTickRelax=0;if(b.energy>=30&&b.status==="Relaxing"){b.status="Studying";}}}if(b.coffeeWaiting){b.coffeeWaitSeconds++;if(b.coffeeWaitSeconds>=COFFEE_WAIT_SECONDS){expireCoffeeRequest(bot);}}}}

function triggerCoffeeRequest(name){const b=onlineBots[name];if(!b||b.coffeeWaiting)return;b.coffeeWaiting=true;b.coffeeWaitSeconds=0;b.status="Relaxing";const msgId="coffee-"+name.replace(/[^a-zA-Z0-9]/g,'-')+"-"+Date.now();b.coffeeMessageId=msgId;const chatMessages=document.getElementById('chat-messages');const msg=document.createElement('div');msg.className="message bot-msg-relax";msg.id=msgId;msg.innerHTML=`😩 <b>${name}:</b> I'm completely drained... I need coffee to keep going!<br><span class="coffee-btn waiting" onclick="giveCoffee('${name}')" title="Give Coffee (costs 1 ☕)">☕</span> <span style="font-size:9px;color:#665b75;" id="coffee-timer-${msgId}">2:00 remaining</span>`;chatMessages.appendChild(msg);chatMessages.scrollTop=chatMessages.scrollHeight;if(chatMessages.children.length>20)chatMessages.removeChild(chatMessages.children[0]);updateMemberList();}
function expireCoffeeRequest(name){const b=onlineBots[name];if(!b)return;if(b.coffeeMessageId){const msgEl=document.getElementById(b.coffeeMessageId);if(msgEl){const coffeeBtn=msgEl.querySelector('.coffee-btn');if(coffeeBtn){coffeeBtn.classList.remove('waiting');coffeeBtn.classList.add('expired');coffeeBtn.onclick=null;coffeeBtn.title="Too late!";}const timerEl=document.getElementById('coffee-timer-'+b.coffeeMessageId);if(timerEl)timerEl.innerText="⏰ Too late!";}}addSystemMessage(`🚪 <b>${name}</b> left — no coffee arrived in time.`,"bot-msg-leave");delete onlineBots[name];updateMemberList();}
window.giveCoffee=function(name){if(!onlineBots[name]||!onlineBots[name].coffeeWaiting)return;if(coffeeStock<=0){addSystemMessage("☕ No coffee in stock! Buy from the 🛒 SHOP first.","system-msg");return;}coffeeStock--;onlineBots[name].energy=Math.min(100,onlineBots[name].energy+70);onlineBots[name].coffeeWaiting=false;onlineBots[name].coffeeWaitSeconds=0;onlineBots[name].status="Studying";const msgId=onlineBots[name].coffeeMessageId;if(msgId){const msgEl=document.getElementById(msgId);if(msgEl){const coffeeBtn=msgEl.querySelector('.coffee-btn');if(coffeeBtn){coffeeBtn.classList.remove('waiting');coffeeBtn.onclick=null;coffeeBtn.style.cursor='default';coffeeBtn.title='Coffee delivered!';}const timerEl=document.getElementById('coffee-timer-'+msgId);if(timerEl)timerEl.innerText="✅ Delivered!";}}onlineBots[name].coffeeMessageId=null;addSystemMessage(`☕✅ <b>${name}</b> got their coffee and is back to studying! (Stock: ${coffeeStock})`,"bot-msg-study");updateShopDisplay();updateMemberList();};
setInterval(()=>{for(let name in onlineBots){const b=onlineBots[name];if(b.coffeeWaiting&&b.coffeeMessageId){const remaining=Math.max(0,COFFEE_WAIT_SECONDS-b.coffeeWaitSeconds);const mins=Math.floor(remaining/60);const secs=remaining%60;const timerEl=document.getElementById('coffee-timer-'+b.coffeeMessageId);if(timerEl)timerEl.innerText=`${mins}:${String(secs).padStart(2,'0')} remaining`;}}},1000);

function formatTime(totalSeconds){let hrs=Math.floor(totalSeconds/3600);let mins=Math.floor((totalSeconds%3600)/60);let secs=totalSeconds%60;return`${String(hrs).padStart(2,'0')}:${String(mins).padStart(2,'0')}:${String(secs).padStart(2,'0')}`;}
const BOT_COLORS=["#3498db","#2ecc71","#e67e22","#e74c3c","#9b59b6","#f1c40f","#1abc9c","#e84393","#ffeaa7","#a29bfe"];
function getEnergyColor(e){if(e>60)return"#2ecc71";if(e>30)return"#f1c40f";return"#e74c3c";}
function updateMemberList(){const memberList=document.getElementById('member-list');memberList.innerHTML="";const isMP=isInMultiplayer();if(isMP)return;let totalOnline=Object.keys(onlineBots).length+1;document.getElementById('member-count').innerText=`👥 Active Leaders (${totalOnline}/${configMaxMembers})`;let combinedList=Object.keys(onlineBots).map(name=>{if(!onlineBots[name].color){onlineBots[name].color=BOT_COLORS[Math.floor(Math.random()*BOT_COLORS.length)];}return{name:name,timeSpent:onlineBots[name].timeSpent,status:onlineBots[name].status,isUser:false,isFrozen:onlineBots[name].isFrozen,isLocked:onlineBots[name].isLocked,energy:onlineBots[name].energy,coffeeWaiting:onlineBots[name].coffeeWaiting,color:onlineBots[name].color};});combinedList.push({name:myName+" (YOU)",timeSpent:userSeconds/60,status:userStatus,isUser:true,isFrozen:false,isLocked:false,energy:100,coffeeWaiting:false,color:"var(--theme-main)"});combinedList.sort((a,b)=>b.timeSpent-a.timeSpent);combinedList.forEach(member=>{const card=document.createElement('div');card.className="member-card";const cleanId=member.name.replace(/[^a-zA-Z0-9]/g,'-');const icon=member.coffeeWaiting?"☕":(member.isLocked?"🔒":(member.isFrozen?"❄️":(member.status==="Studying"?"📖":"⏳")));let customStyle=`color:${member.color};font-weight:bold;text-shadow:0 0 6px ${member.color};`;const energyBarHTML=member.isUser?"":`<div class="energy-bar-wrap"><div class="energy-bar-fill" style="width:${member.energy}%;background:${getEnergyColor(member.energy)};"></div></div>`;card.innerHTML=`<div class="member-info"><span class="m-name" style="${customStyle}">${member.name}${member.isFrozen?'<span style="color:#3498db;font-size:8px;">[FROZEN]</span>':''}${member.isLocked?'<span style="color:#e74c3c;font-size:8px;">[LOCKED]</span>':''}${member.coffeeWaiting?'<span style="color:#f39c12;font-size:8px;">[NEEDS ☕]</span>':''}</span><span class="m-time" id="time-${cleanId}">${formatTime(Math.floor(member.timeSpent*60))}</span>${energyBarHTML}</div><span class="m-status-icon">${icon}</span>`;memberList.appendChild(card);});}
function updateMemberTimesOnly(){for(let name in onlineBots){const cleanId=name.replace(/[^a-zA-Z0-9]/g,'-');const timeSpan=document.getElementById(`time-${cleanId}`);if(timeSpan&&onlineBots[name].status==="Studying"&&!onlineBots[name].isFrozen){timeSpan.innerText=formatTime(Math.floor(onlineBots[name].timeSpent*60));}}const myCleanId=(myName+" (YOU)").replace(/[^a-zA-Z0-9]/g,'-');const myTimeSpan=document.getElementById(`time-${myCleanId}`);if(myTimeSpan&&userStatus==="Studying"){myTimeSpan.innerText=formatTime(userSeconds);}}
function addSystemMessage(text,typeClass){const chatMessages=document.getElementById('chat-messages');const msg=document.createElement('div');msg.className=`message ${typeClass||'system-msg'}`;msg.innerHTML=text;chatMessages.appendChild(msg);chatMessages.scrollTop=chatMessages.scrollHeight;if(chatMessages.children.length>20)chatMessages.removeChild(chatMessages.children[0]);}
function simulateRoomActivities(){setInterval(()=>{const botNames=Object.keys(onlineBots);const totalPeople=botNames.length+1;const roll=Math.random();const allChars=getAllCharacters();if(roll<0.65&&botNames.length>0){const randomBotName=botNames[Math.floor(Math.random()*botNames.length)];const bot=onlineBots[randomBotName];if(bot.isFrozen||bot.coffeeWaiting)return;if(bot.status==="Studying"){if(Math.random()>0.4&&bot.quotes){const quote=bot.quotes.studyQuotes[Math.floor(Math.random()*bot.quotes.studyQuotes.length)];addSystemMessage(`💬 <b>${randomBotName}:</b> "${quote}"`,"bot-msg-study");}else{bot.status="Relaxing";const quote=bot.quotes?`"${bot.quotes.relaxQuotes[Math.floor(Math.random()*bot.quotes.relaxQuotes.length)]}"` :"Going to take a quick break.";addSystemMessage(`⏳ <b>${randomBotName}:</b> ${quote}`,"bot-msg-relax");updateMemberList();}}else{if(bot.energy>10){bot.status="Studying";const quote=bot.quotes?`"${bot.quotes.studyQuotes[Math.floor(Math.random()*bot.quotes.studyQuotes.length)]}"` :"Back to my books!";addSystemMessage(`📖 <b>${randomBotName}:</b> ${quote}`,"bot-msg-study");updateMemberList();}}}else if(totalPeople<configMaxMembers){let pool=configAllowOthers?allChars.map(c=>c.name).concat(EXTRA_CHARACTERS):[...configSelectedPool];let candidates=pool.filter(name=>!botNames.includes(name)&&!bannedBots.includes(name));if(candidates.length>0){const newBotName=candidates[Math.floor(Math.random()*candidates.length)];const fullData=allChars.find(c=>c.name===newBotName);onlineBots[newBotName]={status:"Studying",timeSpent:0,energy:Math.floor(Math.random()*30)+70,energyTickStudy:0,energyTickRelax:0,coffeeWaiting:false,coffeeWaitSeconds:0,coffeeMessageId:null,quotes:fullData||null,pass:fullData?fullData.pass:"pass_"+Math.floor(Math.random()*999),isFrozen:false,isLocked:false};addSystemMessage(`🚀 <b>${newBotName}</b> joined the room.`,"bot-msg-study");updateMemberList();}}},Math.floor(Math.random()*10000)+12000);}

btnAdminPanel.addEventListener('click',()=>{adminModal.classList.remove('hidden');renderAdminPanelUsers();});
btnCloseAdmin.addEventListener('click',()=>{adminModal.classList.add('hidden');});
function renderAdminPanelUsers(){adminUsersList.innerHTML="";for(let name in onlineBots){const bot=onlineBots[name];const row=document.createElement('div');row.className="admin-row";const freezeText=bot.isFrozen?"UNFREEZE":"FREEZE";const freezeClass=bot.isFrozen?"admin-btn unfreeze":"admin-btn freeze";const lockText=bot.isLocked?"UNLOCK":"LOCK";const lockClass=bot.isLocked?"admin-btn unfreeze":"admin-btn freeze";row.innerHTML=`<div class="credentials"><span style="color:#fff;font-weight:bold;">👤 ${name}${bot.isFrozen?' (FROZEN)':''}${bot.isLocked?' (LOCKED)':''}${bot.coffeeWaiting?' ☕':''}</span><span>🔑 Fake Pass: <span style="color:var(--theme-main)">${bot.pass}</span></span><span>⚡ Energy: <span style="color:${getEnergyColor(bot.energy)}">${Math.floor(bot.energy)}%</span></span></div><div class="admin-actions"><button class="${lockClass}" onclick="adminToggleLock('${name}')">${lockText}</button><button class="${freezeClass}" onclick="adminToggleFreeze('${name}')">${freezeText}</button><button class="admin-btn reset" onclick="adminResetTime('${name}')">RESET</button><button class="admin-btn ban" onclick="adminBan('${name}')">BAN</button></div>`;adminUsersList.appendChild(row);}}
window.adminToggleFreeze=function(name){if(onlineBots[name]){onlineBots[name].isFrozen=!onlineBots[name].isFrozen;addSystemMessage(`${onlineBots[name].isFrozen?'❄️ FROZEN':'🔥 UNFROZEN'}: ${name}`,"system-msg");updateMemberList();renderAdminPanelUsers();}};
window.adminToggleLock=function(name){if(onlineBots[name]){onlineBots[name].isLocked=!onlineBots[name].isLocked;addSystemMessage(`${onlineBots[name].isLocked?'🔒 LOCKED':'🔓 UNLOCKED'}: ${name}`,"system-msg");updateMemberList();renderAdminPanelUsers();}};
window.adminResetTime=function(name){if(onlineBots[name]){onlineBots[name].timeSpent=0;addSystemMessage(`🧹 ${name}'s time RESET.`,"system-msg");updateMemberList();renderAdminPanelUsers();}};
window.adminBan=function(name){if(onlineBots[name]){bannedBots.push(name);delete onlineBots[name];addSystemMessage(`🚫 ${name} BANNED.`,"bot-msg-leave");updateMemberList();renderAdminPanelUsers();}};

const weatherSelect=document.getElementById('weather-select');const weatherOverlay=document.getElementById('weather-overlay');let weatherInterval=null;
weatherSelect.addEventListener('change',(e)=>{changeWeather(e.target.value);});
function changeWeather(type){clearInterval(weatherInterval);weatherOverlay.innerHTML="";document.body.className=document.body.className.replace(/weather-\w+/g,'');if(type==="clear"){document.body.classList.add('weather-clear');addSystemMessage("☀️ Weather cleared.","system-msg");}else if(type==="rainy"){document.body.classList.add('weather-rainy');addSystemMessage("🌧️ It started to rain outside.","system-msg");weatherInterval=setInterval(()=>{for(let i=0;i<3;i++){const drop=document.createElement('div');drop.className='drop';drop.style.left=Math.random()*100+'vw';drop.style.animationDuration=(Math.random()*0.5+0.5)+'s';drop.style.opacity=Math.random()*0.4+0.2;weatherOverlay.appendChild(drop);setTimeout(()=>{drop.remove();},1000);}},60);}else if(type==="snowy"){document.body.classList.add('weather-snowy');addSystemMessage("❄️ Soft snow is falling.","system-msg");weatherInterval=setInterval(()=>{for(let i=0;i<2;i++){const flake=document.createElement('div');flake.className='flake';flake.style.left=Math.random()*100+'vw';flake.style.animationDuration=(Math.random()*2+2)+'s';flake.style.width=(Math.random()*3+2)+'px';flake.style.height=flake.style.width;flake.style.opacity=Math.random()*0.6+0.3;weatherOverlay.appendChild(flake);setTimeout(()=>{flake.remove();},4000);}},150);}};

const pomoMinutesDisplay=document.getElementById('pomo-minutes');const pomoSecondsDisplay=document.getElementById('pomo-seconds');const btnStartPomo=document.getElementById('btn-start-pomo');const btnResetPomo=document.getElementById('btn-reset-pomo');let pomoTimer=null;let pomoTimeLeft=25*60;let pomoIsRunning=false;
if(btnStartPomo&&btnResetPomo){btnStartPomo.addEventListener('click',()=>{if(pomoIsRunning){clearInterval(pomoTimer);btnStartPomo.innerText="START";btnStartPomo.style.backgroundColor="var(--theme-main)";btnStartPomo.style.color="#000";pomoIsRunning=false;}else{pomoIsRunning=true;btnStartPomo.innerText="PAUSE";btnStartPomo.style.backgroundColor="#e67e22";btnStartPomo.style.color="#fff";pomoTimer=setInterval(()=>{if(pomoTimeLeft>0){pomoTimeLeft--;updatePomoDisplay();}else{clearInterval(pomoTimer);pomoIsRunning=false;btnStartPomo.innerText="START";btnStartPomo.style.backgroundColor="var(--theme-main)";btnStartPomo.style.color="#000";pomoTimeLeft=25*60;updatePomoDisplay();alert("🚨 Pomodoro Session Finished!");addSystemMessage("🎯 Pomodoro session finished!","system-msg");}},1000);}});btnResetPomo.addEventListener('click',()=>{clearInterval(pomoTimer);pomoIsRunning=false;pomoTimeLeft=25*60;btnStartPomo.innerText="START";btnStartPomo.style.backgroundColor="var(--theme-main)";btnStartPomo.style.color="#000";updatePomoDisplay();});}
function updatePomoDisplay(){if(!pomoMinutesDisplay||!pomoSecondsDisplay)return;pomoMinutesDisplay.innerText=String(Math.floor(pomoTimeLeft/60)).padStart(2,'0');pomoSecondsDisplay.innerText=String(pomoTimeLeft%60).padStart(2,'0');}

// --- STUDY WITH FRIENDS ---
document.getElementById('btn-study-friends').addEventListener('click',async()=>{const nameVal=document.getElementById('username').value.trim();if(!nameVal){alert("Enter your name first!");return;}await loadActiveRooms();document.getElementById('friends-modal').classList.remove('hidden');});
document.getElementById('btn-close-friends').addEventListener('click',()=>{document.getElementById('friends-modal').classList.add('hidden');});
document.getElementById('btn-host-mode').addEventListener('click',()=>{document.getElementById('host-panel').classList.remove('hidden');document.getElementById('join-panel').classList.add('hidden');});
document.getElementById('btn-join-mode').addEventListener('click',()=>{document.getElementById('join-panel').classList.remove('hidden');document.getElementById('host-panel').classList.add('hidden');});

async function loadActiveRooms(){const container=document.getElementById('active-rooms-list');container.innerHTML='';const saved=JSON.parse(localStorage.getItem('cozy_my_rooms'))||[];if(saved.length===0)return;const active=await getActiveRooms(saved);if(active.length===0){localStorage.setItem('cozy_my_rooms',JSON.stringify([]));return;}container.innerHTML='<div style="font-size:9px;color:#8e81a0;margin-bottom:6px;">🟢 YOUR ACTIVE ROOMS:</div>';active.forEach(r=>{const div=document.createElement('div');div.style.cssText='background:#0d1a0d;border:1px solid #2ecc71;padding:8px 12px;border-radius:4px;margin-bottom:6px;display:flex;justify-content:space-between;align-items:center;cursor:pointer;font-size:10px;';div.innerHTML=`<span style="color:#2ecc71;">🏠 Room <b>${r.id}</b> — <b>${r.memberCount}</b> online</span><span style="color:#8e81a0;font-size:9px;">by ${r.host}</span>`;div.onclick=()=>{document.getElementById('join-room-id').value=r.id;document.getElementById('btn-join-mode').click();};container.appendChild(div);});}

document.getElementById('btn-create-room').addEventListener('click',async()=>{const password=document.getElementById('host-password').value.trim();if(!password){alert("Set a password!");return;}const userName=document.getElementById('username').value.trim();const maxM=parseInt(document.getElementById('host-max-members').value)||10;const allowBots=document.getElementById('host-allow-bots').checked;const statusEl=document.getElementById('friends-status-msg');statusEl.style.color="#f1c40f";statusEl.innerText="Creating room...";try{const roomId=await hostRoom(userName,password,maxM,allowBots);const myRooms=JSON.parse(localStorage.getItem('cozy_my_rooms'))||[];if(!myRooms.includes(roomId))myRooms.push(roomId);localStorage.setItem('cozy_my_rooms',JSON.stringify(myRooms));const link=`${location.href.split('?')[0]}?room=${roomId}`;document.getElementById('room-link-display').innerText=link;document.getElementById('room-id-display').innerText=roomId;document.getElementById('room-created-info').classList.remove('hidden');statusEl.style.color="#2ecc71";statusEl.innerText="✅ Room created! Share the link.";}catch(e){statusEl.style.color="#e74c3c";statusEl.innerText="Error: "+e.message;}});

document.getElementById('btn-copy-link').addEventListener('click',()=>{const link=document.getElementById('room-link-display').innerText;navigator.clipboard.writeText(link).then(()=>{document.getElementById('btn-copy-link').innerText="✅ COPIED!";setTimeout(()=>{document.getElementById('btn-copy-link').innerText="📋 COPY LINK";},2000);});});
document.getElementById('btn-enter-own-room').addEventListener('click',()=>{enterMultiplayerRoom(true);});
document.getElementById('btn-join-room').addEventListener('click',async()=>{let input=document.getElementById('join-room-id').value.trim();const password=document.getElementById('join-password').value.trim();const userName=document.getElementById('username').value.trim();if(!input||!password){alert("Fill in Room ID and password!");return;}if(input.includes('?room='))input=input.split('?room=')[1];const roomId=input.toUpperCase();const statusEl=document.getElementById('friends-status-msg');statusEl.style.color="#f1c40f";statusEl.innerText="Joining room...";try{const meta=await joinRoom(roomId,password,userName);mpRoomMeta=meta;statusEl.style.color="#2ecc71";statusEl.innerText="✅ Joined! Entering...";setTimeout(()=>{enterMultiplayerRoom(false);},800);}catch(e){statusEl.style.color="#e74c3c";statusEl.innerText="Error: "+e.message;}});

function enterMultiplayerRoom(asHost){const userName=document.getElementById('username').value.trim();const currentThemeColor=document.getElementById('theme-color').value;myName=userName;applyTheme(currentThemeColor);document.getElementById('display-username').innerText=userName;document.getElementById('friends-modal').classList.add('hidden');loginScreen.classList.add('hidden');appScreen.classList.remove('hidden');if(asHost){btnAdminPanel.style.display='block';}addSystemMessage(`🌐 <b>Multiplayer Room: ${getCurrentRoomId()}</b>`,"system-msg");saveSession({mode:'multi',userName,theme:currentThemeColor,roomId:getCurrentRoomId(),roomPassword:document.getElementById('host-password').value||document.getElementById('join-password').value,isHost:asHost,userSeconds,userCoins,coffeeStock});startMultiplayerTimers(asHost);if(asHost&&mpRoomMeta&&mpRoomMeta.allowBots){configMaxMembers=mpRoomMeta.maxMembers||10;configSelectedPool=getAllCharacters().map(c=>c.name);configAllowOthers=true;configAllowLeave=true;simulateRoomActivities();setInterval(tickBots,1000);}}

function startMultiplayerTimers(asHost){timerInterval=setInterval(()=>{if(userStatus==="Studying"){userSeconds++;userCoins+=COINS_PER_MINUTE/60;document.getElementById('user-timer').innerText=formatTime(userSeconds);}},1000);multiplayerSyncInterval=setInterval(()=>{syncMyStatus(myName,userStatus,Math.floor(userSeconds/60));saveSession({mode:'multi',userName:myName,theme:document.documentElement.style.getPropertyValue('--theme-main'),roomId:getCurrentRoomId(),roomPassword:document.getElementById('host-password').value||document.getElementById('join-password').value,isHost:asHost,userSeconds,userCoins,coffeeStock});},3000);}

window.onMultiplayerMembersUpdate=function(members,myUserName){const memberList=document.getElementById('member-list');memberList.innerHTML="";const realMembers=Object.entries(members);const botEntries=Object.entries(onlineBots);const total=realMembers.length+botEntries.length;document.getElementById('member-count').innerText=`👥 Online (${total})`;realMembers.forEach(([name,data])=>{const card=document.createElement('div');card.className="member-card";const isMe=name===myUserName;const icon=data.status==="Studying"?"📖":"⏳";const color=isMe?"var(--theme-main)":"#a29bfe";card.innerHTML=`<div class="member-info"><span class="m-name" style="color:${color};font-weight:bold;text-shadow:0 0 6px ${color};">${name}${isMe?" (YOU)":""}${data.isHost?" 👑":""}</span><span class="m-time">${formatTime(Math.floor((data.timeSpent||0)*60))}</span></div><span class="m-status-icon">${icon}</span>`;memberList.appendChild(card);});botEntries.forEach(([name,bot])=>{if(!bot.color)bot.color=BOT_COLORS[Math.floor(Math.random()*BOT_COLORS.length)];const card=document.createElement('div');card.className="member-card";const icon=bot.coffeeWaiting?"☕":(bot.status==="Studying"?"📖":"⏳");const energyBarHTML=`<div class="energy-bar-wrap"><div class="energy-bar-fill" style="width:${bot.energy}%;background:${getEnergyColor(bot.energy)};"></div></div>`;card.innerHTML=`<div class="member-info"><span class="m-name" style="color:${bot.color};font-weight:bold;">🤖 ${name}${bot.coffeeWaiting?' <span style="color:#f39c12;font-size:8px;">[NEEDS ☕]</span>':''}</span><span class="m-time">${formatTime(Math.floor(bot.timeSpent*60))}</span>${energyBarHTML}</div><span class="m-status-icon">${icon}</span>`;memberList.appendChild(card);});};

window.onMultiplayerMessagesUpdate=function(msgs){const keys=Object.keys(msgs);keys.forEach(k=>{if(!lastSeenMessages[k]){lastSeenMessages[k]=true;const m=msgs[k];addSystemMessage(m.text,m.type||"system-msg");}});};
